### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by AnyhowStep** [jonaskello/tsconfig-paths#10]
My current directory structure is like so,
```
root
    server
        some_folders
        main.ts
    client
        some_folders
        main.ts
    shared
        some_folders
    tsconfig.json
```

My `tsconfig.json` has the following,
```
{
    "compilerOptions": {
        "outDir": "./dist",
        "sourceMap": true,

        "allowJs": false,

        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "alwaysStrict": true,

        "newLine": "lf",

        "noEmitOnError": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitUseStrict": false,
        "noUnusedLocals": true,
        "noUnusedParameters": true,

        "strictNullChecks": true,

        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es6",
        "jsx": "react",

        "baseUrl": ".",
        "paths": {
            "*": [
                "./shared/*",
                "./shared/config/*",
                "./shared/dao_validation/*",
                "./shared/expression/*",
                "./shared/interaction/*",
                "./shared/lib/*",
                "./shared/localization/*",
                "./shared/model/*",
                "./shared/operator/*",
                "./shared/schema/*",
                "./shared/util/*",
                "./shared/validation/*",

                "./client/*",
                "./client/api/*",
                "./client/dialog/*",
                "./client/form/*",
                "./client/game/*",

                "./server/*",
                "./server/dao/*",
                "./server/database/*",
                "./server/interaction/*",
                "./server/lib/*",
                "./server/middleware/*",
                "./server/model/*",
                "./server/route/*",
                "./server/util/*"
            ]
        },

        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "include": [
        "./client/**/*",
        "./shared/**/*",
        "./server/**/*"
    ],
    "compileOnSave": true
}

```

When I run, `./node_modules/.bin/ts-node -r tsconfig-paths/register ./server/main.ts`, I thought it'd just work like magic. But, instead, I see,

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module.m._compile (/home/anyhowstep/node-projects/prime-ar/prime-ar/node_modules/ts-node/src/index.ts:382:23)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/anyhowstep/node-projects/prime-ar/prime-ar/node_modules/ts-node/src/index.ts:385:12)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module._load (/home/anyhowstep/node-projects/prime-ar/prime-ar/node_modules/tsconfig-paths/lib/register.js:24:35)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

Running `./node_modules/.bin/tsc` compiles everything fine without warnings or errors.

I'm still new to the whole JS/TS ecosystem. How can I provide more information to hopefully resolve this?

**Comment by jonaskello** [comment]
What version of node are you running under? (run `node --version` to check)

**Comment by AnyhowStep** [comment]
Ah, you beat me to it. I did that not too long ago and saw that I was on node 4.x! After updating it to 6.x, it works splendidly now.

The problem was that the source code was being compiled to ES6 along with Promises and all that good stuff but my old node 4.x that ships with Ubuntu 16 by default doesn't support all the ES6 features.

Particularly, default parameter values. So, the real error was that node didn't understand,

`function foo (x : number = 99) : void {}`

Sorry about the confusion.
